spring:
  cassandra:
    contact-point: cassandra
    port: 9042
    keyspace-name: my_keyspace
    schema-action: create-if-not-exists
    local-datacenter: datacenter1
logging:
  level:
    org:
      springframework:
        data:
          cassandra: DEBUG  # Spring Data Cassandra logs
#    com:
#      datastax: DEBUG  # Cassandra driver logs
#      datastax.driver.core: DEBUG  # Connection pool and driver logs
